steps:
  - name: gcr.io/cloud-builders/gcloud
    args:
      - "-c"
      - >
        git clone https://github.com/pradip-148/gcp-ci-cd-test.git

        gcloud app deploy -q

    id: update app engine deployment
    entrypoint: /bin/sh
