steps:
  - name: gcr.io/cloud-builders/gcloud
    args:
      - "-c"
      - >
        gcloud config set project se-ps1-appdev

        git clone 

        gcloud app deploy -q

    id: update app engine deployment
    entrypoint: /bin/sh
