steps:
  - name: gcr.io/cloud-builders/gcloud
    args:
      - "-c"
      - >
        git clone https://github.com/GoogleCloudPlatform/python-docs-samples.git

        cd python-docs-samples/appengine/standard_python3/hello_world/

        gcloud app deploy -q

    id: update app engine deployment
    entrypoint: /bin/sh
